AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal ECS Fargate Cluster

Parameters:
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for ECS resources
    Default: subnet-016fa8e2544040acd  # Replace with your default subnet ID
  ImageTag:
    Type: String
    Description: Image tag for the backend service
    Default: 47464652f0f80eb83be3f16af019d3c19bbf8fdd
  MongoUri:
    Type: String
    Description: MongoDB connection URI
    NoEcho: true
  AwsRegion:
    Type: String
    Default: us-east-1
    Description: AWS Region
  SqsQueueUrl:
    Type: String
    Description: SQS Queue URL
    NoEcho: true
  TopicArn:
    Type: String
    Description: SNS Topic ARN
    NoEcho: true

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ecs-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/backend-task
      RetentionInDays: 7

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: backend-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::GetAtt: [ECSExecutionRole, Arn]
      TaskRoleArn: 
        Fn::GetAtt: [ECSTaskRole, Arn]
      ContainerDefinitions:
        - Name: backend-container
          Image: 
            Fn::Sub: '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/api-service-repo:${ImageTag}'
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: AWS_REGION
              Value: !Ref AwsRegion
            - Name: SQS_QUEUE_URL
              Value: !Ref SqsQueueUrl
            - Name: TOPIC_ARN
              Value: !Ref TopicArn
            - Name: MONGO_URI
              Value: !Ref MongoUri
            - Name: REDIS_HOST
              Value: redis-18619.c283.us-east-1-4.ec2.cloud.redislabs.com
            - Name: REDIS_PORT
              Value: "18619"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: backend-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref BackendTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref SubnetId
          AssignPublicIp: ENABLED

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value:
      Ref: ECSCluster
    Export:
      Name: 
        Fn::Sub: '${AWS::StackName}-ECSCluster'
  ECSExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: 
      Fn::GetAtt: [ECSExecutionRole, Arn]
    Export:
      Name: 
        Fn::Sub: '${AWS::StackName}-ECSExecutionRole'
  ECSTaskRoleArn:
    Description: ECS Task Role ARN
    Value: 
      Fn::GetAtt: [ECSTaskRole, Arn]
    Export:
      Name: 
        Fn::Sub: '${AWS::StackName}-ECSTaskRole'
  BackendTaskDefinitionArn:
    Description: Backend Task Definition ARN
    Value: 
      Ref: BackendTaskDefinition
    Export:
      Name: 
        Fn::Sub: '${AWS::StackName}-BackendTaskDefinition'
  BackendServiceName:
    Description: Backend Service Name
    Value: 
      Ref: BackendService
    Export:
      Name: 
        Fn::Sub: '${AWS::StackName}-BackendService'