AWSTemplateFormatVersion: '2010-09-09'
Description: Main Infrastructure Stack - ECS Cluster and Services

Parameters:
  DesiredCapacity:
    Type: Number
    Default: 1
    Description: Initial number of EC2 instances
  KeyName:
    Type: String
    Default: keypair
    Description: Name of existing EC2 KeyPair (without .pem)

Resources:

  # -------------------------
  # ECS Cluster Stack
  # -------------------------
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ecs-cluster.yaml
      Parameters:
        DesiredCapacity: !Ref DesiredCapacity
        KeyName: !Ref KeyName

Outputs:
  ClusterName:
    Description: Name of the ECS Cluster
    Value: !GetAtt ECSClusterStack.Outputs.ClusterName